;=======|	function	|============================================
winR(index,key,TrueKey)
{
	global winRsignal
	global winRsignal2
	global winRArray
	KeyWait %key%
	; input key map mode:
	if (A_TimeSinceThisHotkey > 400)
	{
		if (winRsignal2 == 0){
			path := Explorer_GetSelection(hwnd)
		}else{
			WinGet path ,processPath,A
		}
		IniWrite, %path%, config.ini, winR, %index%
		MsgBox, ,add sucessfully , %path%				
		winRArray[index] := path
		winRsignal :=0
		winRsignal2 := 0
		return
	}else{
		if winRArray[index] == "ERROR"
			func_tooltip("key-no-map")
		else{
			temp := winRArray[index]
			IfWinExist, ahk_exe %temp%
			{
				WinActivate, ahk_exe %temp%
				func_tooltip("winR activited")
			}
			else{
				Run, % winRArray[index]
				func_tooltip("winR Runing")
			}
		}
	} 
	winRsignal :=0
	return
}

;=======|	get curent filepath	|============================================
Explorer_GetSelection(hwnd="")   
{  
    WinGet, process, processName, % "ahk_id" hwnd := hwnd? hwnd:WinExist("A")  
    WinGetClass class, ahk_id %hwnd%  
    if (process != "explorer.exe")  
        return  
    if (class ~= "Progman|WorkerW") {  
            ControlGet, files, List, Selected Col1, SysListView321, ahk_class %class%  
            Loop, Parse, files, `n, `r  
                ToReturn .= A_Desktop "\" A_LoopField "`n"  
        } else if (class ~= "(Cabinet|Explore)WClass") {  
            for window in ComObjCreate("Shell.Application").Windows 
			{
				try{
                if (window.hwnd==hwnd)  
                    sel := window.Document.SelectedItems  
				}catch e {
					continue
			}
			}
            for item in sel  
                ToReturn .= item.path "`n"  
        }  
    return Trim(ToReturn,"`n")  
} 

;=======|	key	|============================================
#r::
winRsignal := 1
func_tooltip("in winR mode")
KeyWait r
if (A_TimeSinceThisHotkey > 200)
{
	func_tooltip("in currentWinPath mode")
	winRsignal2 := 1
}
return	


#if winRsignal==1
capslock::
winRsignal := 0
func_tooltip("exit winR mode")
return

*a::winR(1,"a","a")
*b::winR(2,"b","b")
*c::winR(3,"c","c")
*d::winR(4,"d","d")
*e::winR(5,"e","e")
*f::winR(6,"f","f")
*g::winR(7,"g","g")
*h::winR(8,"h","h")
*i::winR(9,"i","i")
*j::winR(10,"j","j")
*k::winR(11,"k","k")
*l::winR(12,"l","l")
*m::winR(13,"m","m")
*n::winR(14,"n","n")
*o::winR(15,"o","o")
*p::winR(16,"p","p")
*q::winR(17,"q","q")
*r::winR(18,"r","r")
*s::winR(19,"s","s")
*t::winR(20,"t","t")
*u::winR(21,"u","u")
*v::winR(22,"v","v")
*w::winR(23,"w","w")
*x::winR(24,"x","x")
*y::winR(25,"y","y")
*z::winR(26,"z","z")
a & b::winR(28,"b","a & b")
a & c::winR(29,"c","a & c")
a & d::winR(30,"d","a & d")
a & e::winR(31,"e","a & e")
a & f::winR(32,"f","a & f")
a & g::winR(33,"g","a & g")
a & h::winR(34,"h","a & h")
a & i::winR(35,"i","a & i")
a & j::winR(36,"j","a & j")
a & k::winR(37,"k","a & k")
a & l::winR(38,"l","a & l")
a & m::winR(39,"m","a & m")
a & n::winR(40,"n","a & n")
a & o::winR(41,"o","a & o")
a & p::winR(42,"p","a & p")
a & q::winR(43,"q","a & q")
a & r::winR(44,"r","a & r")
a & s::winR(45,"s","a & s")
a & t::winR(46,"t","a & t")
a & u::winR(47,"u","a & u")
a & v::winR(48,"v","a & v")
a & w::winR(49,"w","a & w")
a & x::winR(50,"x","a & x")
a & y::winR(51,"y","a & y")
a & z::winR(52,"z","a & z")
b & a::winR(52,"a","b & a")
b & c::winR(54,"c","b & c")
b & d::winR(55,"d","b & d")
b & e::winR(56,"e","b & e")
b & f::winR(57,"f","b & f")
b & g::winR(58,"g","b & g")
b & h::winR(59,"h","b & h")
b & i::winR(60,"i","b & i")
b & j::winR(61,"j","b & j")
b & k::winR(62,"k","b & k")
b & l::winR(63,"l","b & l")
b & m::winR(64,"m","b & m")
b & n::winR(65,"n","b & n")
b & o::winR(66,"o","b & o")
b & p::winR(67,"p","b & p")
b & q::winR(68,"q","b & q")
b & r::winR(69,"r","b & r")
b & s::winR(70,"s","b & s")
b & t::winR(71,"t","b & t")
b & u::winR(72,"u","b & u")
b & v::winR(73,"v","b & v")
b & w::winR(74,"w","b & w")
b & x::winR(75,"x","b & x")
b & y::winR(76,"y","b & y")
b & z::winR(77,"z","b & z")
c & a::winR(77,"a","c & a")
c & b::winR(78,"b","c & b")
c & d::winR(80,"d","c & d")
c & e::winR(81,"e","c & e")
c & f::winR(82,"f","c & f")
c & g::winR(83,"g","c & g")
c & h::winR(84,"h","c & h")
c & i::winR(85,"i","c & i")
c & j::winR(86,"j","c & j")
c & k::winR(87,"k","c & k")
c & l::winR(88,"l","c & l")
c & m::winR(89,"m","c & m")
c & n::winR(90,"n","c & n")
c & o::winR(91,"o","c & o")
c & p::winR(92,"p","c & p")
c & q::winR(93,"q","c & q")
c & r::winR(94,"r","c & r")
c & s::winR(95,"s","c & s")
c & t::winR(96,"t","c & t")
c & u::winR(97,"u","c & u")
c & v::winR(98,"v","c & v")
c & w::winR(99,"w","c & w")
c & x::winR(100,"x","c & x")
c & y::winR(101,"y","c & y")
c & z::winR(102,"z","c & z")
d & a::winR(102,"a","d & a")
d & b::winR(103,"b","d & b")
d & c::winR(104,"c","d & c")
d & e::winR(106,"e","d & e")
d & f::winR(107,"f","d & f")
d & g::winR(108,"g","d & g")
d & h::winR(109,"h","d & h")
d & i::winR(110,"i","d & i")
d & j::winR(111,"j","d & j")
d & k::winR(112,"k","d & k")
d & l::winR(113,"l","d & l")
d & m::winR(114,"m","d & m")
d & n::winR(115,"n","d & n")
d & o::winR(116,"o","d & o")
d & p::winR(117,"p","d & p")
d & q::winR(118,"q","d & q")
d & r::winR(119,"r","d & r")
d & s::winR(120,"s","d & s")
d & t::winR(121,"t","d & t")
d & u::winR(122,"u","d & u")
d & v::winR(123,"v","d & v")
d & w::winR(124,"w","d & w")
d & x::winR(125,"x","d & x")
d & y::winR(126,"y","d & y")
d & z::winR(127,"z","d & z")
e & a::winR(127,"a","e & a")
e & b::winR(128,"b","e & b")
e & c::winR(129,"c","e & c")
e & d::winR(130,"d","e & d")
e & f::winR(132,"f","e & f")
e & g::winR(133,"g","e & g")
e & h::winR(134,"h","e & h")
e & i::winR(135,"i","e & i")
e & j::winR(136,"j","e & j")
e & k::winR(137,"k","e & k")
e & l::winR(138,"l","e & l")
e & m::winR(139,"m","e & m")
e & n::winR(140,"n","e & n")
e & o::winR(141,"o","e & o")
e & p::winR(142,"p","e & p")
e & q::winR(143,"q","e & q")
e & r::winR(144,"r","e & r")
e & s::winR(145,"s","e & s")
e & t::winR(146,"t","e & t")
e & u::winR(147,"u","e & u")
e & v::winR(148,"v","e & v")
e & w::winR(149,"w","e & w")
e & x::winR(150,"x","e & x")
e & y::winR(151,"y","e & y")
e & z::winR(152,"z","e & z")
f & a::winR(152,"a","f & a")
f & b::winR(153,"b","f & b")
f & c::winR(154,"c","f & c")
f & d::winR(155,"d","f & d")
f & e::winR(156,"e","f & e")
f & g::winR(158,"g","f & g")
f & h::winR(159,"h","f & h")
f & i::winR(160,"i","f & i")
f & j::winR(161,"j","f & j")
f & k::winR(162,"k","f & k")
f & l::winR(163,"l","f & l")
f & m::winR(164,"m","f & m")
f & n::winR(165,"n","f & n")
f & o::winR(166,"o","f & o")
f & p::winR(167,"p","f & p")
f & q::winR(168,"q","f & q")
f & r::winR(169,"r","f & r")
f & s::winR(170,"s","f & s")
f & t::winR(171,"t","f & t")
f & u::winR(172,"u","f & u")
f & v::winR(173,"v","f & v")
f & w::winR(174,"w","f & w")
f & x::winR(175,"x","f & x")
f & y::winR(176,"y","f & y")
f & z::winR(177,"z","f & z")
g & a::winR(177,"a","g & a")
g & b::winR(178,"b","g & b")
g & c::winR(179,"c","g & c")
g & d::winR(180,"d","g & d")
g & e::winR(181,"e","g & e")
g & f::winR(182,"f","g & f")
g & h::winR(184,"h","g & h")
g & i::winR(185,"i","g & i")
g & j::winR(186,"j","g & j")
g & k::winR(187,"k","g & k")
g & l::winR(188,"l","g & l")
g & m::winR(189,"m","g & m")
g & n::winR(190,"n","g & n")
g & o::winR(191,"o","g & o")
g & p::winR(192,"p","g & p")
g & q::winR(193,"q","g & q")
g & r::winR(194,"r","g & r")
g & s::winR(195,"s","g & s")
g & t::winR(196,"t","g & t")
g & u::winR(197,"u","g & u")
g & v::winR(198,"v","g & v")
g & w::winR(199,"w","g & w")
g & x::winR(200,"x","g & x")
g & y::winR(201,"y","g & y")
g & z::winR(202,"z","g & z")
h & a::winR(202,"a","h & a")
h & b::winR(203,"b","h & b")
h & c::winR(204,"c","h & c")
h & d::winR(205,"d","h & d")
h & e::winR(206,"e","h & e")
h & f::winR(207,"f","h & f")
h & g::winR(208,"g","h & g")
h & i::winR(210,"i","h & i")
h & j::winR(211,"j","h & j")
h & k::winR(212,"k","h & k")
h & l::winR(213,"l","h & l")
h & m::winR(214,"m","h & m")
h & n::winR(215,"n","h & n")
h & o::winR(216,"o","h & o")
h & p::winR(217,"p","h & p")
h & q::winR(218,"q","h & q")
h & r::winR(219,"r","h & r")
h & s::winR(220,"s","h & s")
h & t::winR(221,"t","h & t")
h & u::winR(222,"u","h & u")
h & v::winR(223,"v","h & v")
h & w::winR(224,"w","h & w")
h & x::winR(225,"x","h & x")
h & y::winR(226,"y","h & y")
h & z::winR(227,"z","h & z")
i & a::winR(227,"a","i & a")
i & b::winR(228,"b","i & b")
i & c::winR(229,"c","i & c")
i & d::winR(230,"d","i & d")
i & e::winR(231,"e","i & e")
i & f::winR(232,"f","i & f")
i & g::winR(233,"g","i & g")
i & h::winR(234,"h","i & h")
i & j::winR(236,"j","i & j")
i & k::winR(237,"k","i & k")
i & l::winR(238,"l","i & l")
i & m::winR(239,"m","i & m")
i & n::winR(240,"n","i & n")
i & o::winR(241,"o","i & o")
i & p::winR(242,"p","i & p")
i & q::winR(243,"q","i & q")
i & r::winR(244,"r","i & r")
i & s::winR(245,"s","i & s")
i & t::winR(246,"t","i & t")
i & u::winR(247,"u","i & u")
i & v::winR(248,"v","i & v")
i & w::winR(249,"w","i & w")
i & x::winR(250,"x","i & x")
i & y::winR(251,"y","i & y")
i & z::winR(252,"z","i & z")
j & a::winR(252,"a","j & a")
j & b::winR(253,"b","j & b")
j & c::winR(254,"c","j & c")
j & d::winR(255,"d","j & d")
j & e::winR(256,"e","j & e")
j & f::winR(257,"f","j & f")
j & g::winR(258,"g","j & g")
j & h::winR(259,"h","j & h")
j & i::winR(260,"i","j & i")
j & k::winR(262,"k","j & k")
j & l::winR(263,"l","j & l")
j & m::winR(264,"m","j & m")
j & n::winR(265,"n","j & n")
j & o::winR(266,"o","j & o")
j & p::winR(267,"p","j & p")
j & q::winR(268,"q","j & q")
j & r::winR(269,"r","j & r")
j & s::winR(270,"s","j & s")
j & t::winR(271,"t","j & t")
j & u::winR(272,"u","j & u")
j & v::winR(273,"v","j & v")
j & w::winR(274,"w","j & w")
j & x::winR(275,"x","j & x")
j & y::winR(276,"y","j & y")
j & z::winR(277,"z","j & z")
k & a::winR(277,"a","k & a")
k & b::winR(278,"b","k & b")
k & c::winR(279,"c","k & c")
k & d::winR(280,"d","k & d")
k & e::winR(281,"e","k & e")
k & f::winR(282,"f","k & f")
k & g::winR(283,"g","k & g")
k & h::winR(284,"h","k & h")
k & i::winR(285,"i","k & i")
k & j::winR(286,"j","k & j")
k & l::winR(288,"l","k & l")
k & m::winR(289,"m","k & m")
k & n::winR(290,"n","k & n")
k & o::winR(291,"o","k & o")
k & p::winR(292,"p","k & p")
k & q::winR(293,"q","k & q")
k & r::winR(294,"r","k & r")
k & s::winR(295,"s","k & s")
k & t::winR(296,"t","k & t")
k & u::winR(297,"u","k & u")
k & v::winR(298,"v","k & v")
k & w::winR(299,"w","k & w")
k & x::winR(300,"x","k & x")
k & y::winR(301,"y","k & y")
k & z::winR(302,"z","k & z")
l & a::winR(302,"a","l & a")
l & b::winR(303,"b","l & b")
l & c::winR(304,"c","l & c")
l & d::winR(305,"d","l & d")
l & e::winR(306,"e","l & e")
l & f::winR(307,"f","l & f")
l & g::winR(308,"g","l & g")
l & h::winR(309,"h","l & h")
l & i::winR(310,"i","l & i")
l & j::winR(311,"j","l & j")
l & k::winR(312,"k","l & k")
l & m::winR(314,"m","l & m")
l & n::winR(315,"n","l & n")
l & o::winR(316,"o","l & o")
l & p::winR(317,"p","l & p")
l & q::winR(318,"q","l & q")
l & r::winR(319,"r","l & r")
l & s::winR(320,"s","l & s")
l & t::winR(321,"t","l & t")
l & u::winR(322,"u","l & u")
l & v::winR(323,"v","l & v")
l & w::winR(324,"w","l & w")
l & x::winR(325,"x","l & x")
l & y::winR(326,"y","l & y")
l & z::winR(327,"z","l & z")
m & a::winR(327,"a","m & a")
m & b::winR(328,"b","m & b")
m & c::winR(329,"c","m & c")
m & d::winR(330,"d","m & d")
m & e::winR(331,"e","m & e")
m & f::winR(332,"f","m & f")
m & g::winR(333,"g","m & g")
m & h::winR(334,"h","m & h")
m & i::winR(335,"i","m & i")
m & j::winR(336,"j","m & j")
m & k::winR(337,"k","m & k")
m & l::winR(338,"l","m & l")
m & n::winR(340,"n","m & n")
m & o::winR(341,"o","m & o")
m & p::winR(342,"p","m & p")
m & q::winR(343,"q","m & q")
m & r::winR(344,"r","m & r")
m & s::winR(345,"s","m & s")
m & t::winR(346,"t","m & t")
m & u::winR(347,"u","m & u")
m & v::winR(348,"v","m & v")
m & w::winR(349,"w","m & w")
m & x::winR(350,"x","m & x")
m & y::winR(351,"y","m & y")
m & z::winR(352,"z","m & z")
n & a::winR(352,"a","n & a")
n & b::winR(353,"b","n & b")
n & c::winR(354,"c","n & c")
n & d::winR(355,"d","n & d")
n & e::winR(356,"e","n & e")
n & f::winR(357,"f","n & f")
n & g::winR(358,"g","n & g")
n & h::winR(359,"h","n & h")
n & i::winR(360,"i","n & i")
n & j::winR(361,"j","n & j")
n & k::winR(362,"k","n & k")
n & l::winR(363,"l","n & l")
n & m::winR(364,"m","n & m")
n & o::winR(366,"o","n & o")
n & p::winR(367,"p","n & p")
n & q::winR(368,"q","n & q")
n & r::winR(369,"r","n & r")
n & s::winR(370,"s","n & s")
n & t::winR(371,"t","n & t")
n & u::winR(372,"u","n & u")
n & v::winR(373,"v","n & v")
n & w::winR(374,"w","n & w")
n & x::winR(375,"x","n & x")
n & y::winR(376,"y","n & y")
n & z::winR(377,"z","n & z")
o & a::winR(377,"a","o & a")
o & b::winR(378,"b","o & b")
o & c::winR(379,"c","o & c")
o & d::winR(380,"d","o & d")
o & e::winR(381,"e","o & e")
o & f::winR(382,"f","o & f")
o & g::winR(383,"g","o & g")
o & h::winR(384,"h","o & h")
o & i::winR(385,"i","o & i")
o & j::winR(386,"j","o & j")
o & k::winR(387,"k","o & k")
o & l::winR(388,"l","o & l")
o & m::winR(389,"m","o & m")
o & n::winR(390,"n","o & n")
o & p::winR(392,"p","o & p")
o & q::winR(393,"q","o & q")
o & r::winR(394,"r","o & r")
o & s::winR(395,"s","o & s")
o & t::winR(396,"t","o & t")
o & u::winR(397,"u","o & u")
o & v::winR(398,"v","o & v")
o & w::winR(399,"w","o & w")
o & x::winR(400,"x","o & x")
o & y::winR(401,"y","o & y")
o & z::winR(402,"z","o & z")
p & a::winR(402,"a","p & a")
p & b::winR(403,"b","p & b")
p & c::winR(404,"c","p & c")
p & d::winR(405,"d","p & d")
p & e::winR(406,"e","p & e")
p & f::winR(407,"f","p & f")
p & g::winR(408,"g","p & g")
p & h::winR(409,"h","p & h")
p & i::winR(410,"i","p & i")
p & j::winR(411,"j","p & j")
p & k::winR(412,"k","p & k")
p & l::winR(413,"l","p & l")
p & m::winR(414,"m","p & m")
p & n::winR(415,"n","p & n")
p & o::winR(416,"o","p & o")
p & q::winR(418,"q","p & q")
p & r::winR(419,"r","p & r")
p & s::winR(420,"s","p & s")
p & t::winR(421,"t","p & t")
p & u::winR(422,"u","p & u")
p & v::winR(423,"v","p & v")
p & w::winR(424,"w","p & w")
p & x::winR(425,"x","p & x")
p & y::winR(426,"y","p & y")
p & z::winR(427,"z","p & z")
q & a::winR(427,"a","q & a")
q & b::winR(428,"b","q & b")
q & c::winR(429,"c","q & c")
q & d::winR(430,"d","q & d")
q & e::winR(431,"e","q & e")
q & f::winR(432,"f","q & f")
q & g::winR(433,"g","q & g")
q & h::winR(434,"h","q & h")
q & i::winR(435,"i","q & i")
q & j::winR(436,"j","q & j")
q & k::winR(437,"k","q & k")
q & l::winR(438,"l","q & l")
q & m::winR(439,"m","q & m")
q & n::winR(440,"n","q & n")
q & o::winR(441,"o","q & o")
q & p::winR(442,"p","q & p")
q & r::winR(444,"r","q & r")
q & s::winR(445,"s","q & s")
q & t::winR(446,"t","q & t")
q & u::winR(447,"u","q & u")
q & v::winR(448,"v","q & v")
q & w::winR(449,"w","q & w")
q & x::winR(450,"x","q & x")
q & y::winR(451,"y","q & y")
q & z::winR(452,"z","q & z")
r & a::winR(452,"a","r & a")
r & b::winR(453,"b","r & b")
r & c::winR(454,"c","r & c")
r & d::winR(455,"d","r & d")
r & e::winR(456,"e","r & e")
r & f::winR(457,"f","r & f")
r & g::winR(458,"g","r & g")
r & h::winR(459,"h","r & h")
r & i::winR(460,"i","r & i")
r & j::winR(461,"j","r & j")
r & k::winR(462,"k","r & k")
r & l::winR(463,"l","r & l")
r & m::winR(464,"m","r & m")
r & n::winR(465,"n","r & n")
r & o::winR(466,"o","r & o")
r & p::winR(467,"p","r & p")
r & q::winR(468,"q","r & q")
r & s::winR(470,"s","r & s")
r & t::winR(471,"t","r & t")
r & u::winR(472,"u","r & u")
r & v::winR(473,"v","r & v")
r & w::winR(474,"w","r & w")
r & x::winR(475,"x","r & x")
r & y::winR(476,"y","r & y")
r & z::winR(477,"z","r & z")
s & a::winR(477,"a","s & a")
s & b::winR(478,"b","s & b")
s & c::winR(479,"c","s & c")
s & d::winR(480,"d","s & d")
s & e::winR(481,"e","s & e")
s & f::winR(482,"f","s & f")
s & g::winR(483,"g","s & g")
s & h::winR(484,"h","s & h")
s & i::winR(485,"i","s & i")
s & j::winR(486,"j","s & j")
s & k::winR(487,"k","s & k")
s & l::winR(488,"l","s & l")
s & m::winR(489,"m","s & m")
s & n::winR(490,"n","s & n")
s & o::winR(491,"o","s & o")
s & p::winR(492,"p","s & p")
s & q::winR(493,"q","s & q")
s & r::winR(494,"r","s & r")
s & t::winR(496,"t","s & t")
s & u::winR(497,"u","s & u")
s & v::winR(498,"v","s & v")
s & w::winR(499,"w","s & w")
s & x::winR(500,"x","s & x")
s & y::winR(501,"y","s & y")
s & z::winR(502,"z","s & z")
t & a::winR(502,"a","t & a")
t & b::winR(503,"b","t & b")
t & c::winR(504,"c","t & c")
t & d::winR(505,"d","t & d")
t & e::winR(506,"e","t & e")
t & f::winR(507,"f","t & f")
t & g::winR(508,"g","t & g")
t & h::winR(509,"h","t & h")
t & i::winR(510,"i","t & i")
t & j::winR(511,"j","t & j")
t & k::winR(512,"k","t & k")
t & l::winR(513,"l","t & l")
t & m::winR(514,"m","t & m")
t & n::winR(515,"n","t & n")
t & o::winR(516,"o","t & o")
t & p::winR(517,"p","t & p")
t & q::winR(518,"q","t & q")
t & r::winR(519,"r","t & r")
t & s::winR(520,"s","t & s")
t & u::winR(522,"u","t & u")
t & v::winR(523,"v","t & v")
t & w::winR(524,"w","t & w")
t & x::winR(525,"x","t & x")
t & y::winR(526,"y","t & y")
t & z::winR(527,"z","t & z")
u & a::winR(527,"a","u & a")
u & b::winR(528,"b","u & b")
u & c::winR(529,"c","u & c")
u & d::winR(530,"d","u & d")
u & e::winR(531,"e","u & e")
u & f::winR(532,"f","u & f")
u & g::winR(533,"g","u & g")
u & h::winR(534,"h","u & h")
u & i::winR(535,"i","u & i")
u & j::winR(536,"j","u & j")
u & k::winR(537,"k","u & k")
u & l::winR(538,"l","u & l")
u & m::winR(539,"m","u & m")
u & n::winR(540,"n","u & n")
u & o::winR(541,"o","u & o")
u & p::winR(542,"p","u & p")
u & q::winR(543,"q","u & q")
u & r::winR(544,"r","u & r")
u & s::winR(545,"s","u & s")
u & t::winR(546,"t","u & t")
u & v::winR(548,"v","u & v")
u & w::winR(549,"w","u & w")
u & x::winR(550,"x","u & x")
u & y::winR(551,"y","u & y")
u & z::winR(552,"z","u & z")
v & a::winR(552,"a","v & a")
v & b::winR(553,"b","v & b")
v & c::winR(554,"c","v & c")
v & d::winR(555,"d","v & d")
v & e::winR(556,"e","v & e")
v & f::winR(557,"f","v & f")
v & g::winR(558,"g","v & g")
v & h::winR(559,"h","v & h")
v & i::winR(560,"i","v & i")
v & j::winR(561,"j","v & j")
v & k::winR(562,"k","v & k")
v & l::winR(563,"l","v & l")
v & m::winR(564,"m","v & m")
v & n::winR(565,"n","v & n")
v & o::winR(566,"o","v & o")
v & p::winR(567,"p","v & p")
v & q::winR(568,"q","v & q")
v & r::winR(569,"r","v & r")
v & s::winR(570,"s","v & s")
v & t::winR(571,"t","v & t")
v & u::winR(572,"u","v & u")
v & w::winR(574,"w","v & w")
v & x::winR(575,"x","v & x")
v & y::winR(576,"y","v & y")
v & z::winR(577,"z","v & z")
w & a::winR(577,"a","w & a")
w & b::winR(578,"b","w & b")
w & c::winR(579,"c","w & c")
w & d::winR(580,"d","w & d")
w & e::winR(581,"e","w & e")
w & f::winR(582,"f","w & f")
w & g::winR(583,"g","w & g")
w & h::winR(584,"h","w & h")
w & i::winR(585,"i","w & i")
w & j::winR(586,"j","w & j")
w & k::winR(587,"k","w & k")
w & l::winR(588,"l","w & l")
w & m::winR(589,"m","w & m")
w & n::winR(590,"n","w & n")
w & o::winR(591,"o","w & o")
w & p::winR(592,"p","w & p")
w & q::winR(593,"q","w & q")
w & r::winR(594,"r","w & r")
w & s::winR(595,"s","w & s")
w & t::winR(596,"t","w & t")
w & u::winR(597,"u","w & u")
w & v::winR(598,"v","w & v")
w & x::winR(600,"x","w & x")
w & y::winR(601,"y","w & y")
w & z::winR(602,"z","w & z")
x & a::winR(602,"a","x & a")
x & b::winR(603,"b","x & b")
x & c::winR(604,"c","x & c")
x & d::winR(605,"d","x & d")
x & e::winR(606,"e","x & e")
x & f::winR(607,"f","x & f")
x & g::winR(608,"g","x & g")
x & h::winR(609,"h","x & h")
x & i::winR(610,"i","x & i")
x & j::winR(611,"j","x & j")
x & k::winR(612,"k","x & k")
x & l::winR(613,"l","x & l")
x & m::winR(614,"m","x & m")
x & n::winR(615,"n","x & n")
x & o::winR(616,"o","x & o")
x & p::winR(617,"p","x & p")
x & q::winR(618,"q","x & q")
x & r::winR(619,"r","x & r")
x & s::winR(620,"s","x & s")
x & t::winR(621,"t","x & t")
x & u::winR(622,"u","x & u")
x & v::winR(623,"v","x & v")
x & w::winR(624,"w","x & w")
x & y::winR(626,"y","x & y")
x & z::winR(627,"z","x & z")
y & a::winR(627,"a","y & a")
y & b::winR(628,"b","y & b")
y & c::winR(629,"c","y & c")
y & d::winR(630,"d","y & d")
y & e::winR(631,"e","y & e")
y & f::winR(632,"f","y & f")
y & g::winR(633,"g","y & g")
y & h::winR(634,"h","y & h")
y & i::winR(635,"i","y & i")
y & j::winR(636,"j","y & j")
y & k::winR(637,"k","y & k")
y & l::winR(638,"l","y & l")
y & m::winR(639,"m","y & m")
y & n::winR(640,"n","y & n")
y & o::winR(641,"o","y & o")
y & p::winR(642,"p","y & p")
y & q::winR(643,"q","y & q")
y & r::winR(644,"r","y & r")
y & s::winR(645,"s","y & s")
y & t::winR(646,"t","y & t")
y & u::winR(647,"u","y & u")
y & v::winR(648,"v","y & v")
y & w::winR(649,"w","y & w")
y & x::winR(650,"x","y & x")
y & z::winR(652,"z","y & z")
z & a::winR(652,"a","z & a")
z & b::winR(653,"b","z & b")
z & c::winR(654,"c","z & c")
z & d::winR(655,"d","z & d")
z & e::winR(656,"e","z & e")
z & f::winR(657,"f","z & f")
z & g::winR(658,"g","z & g")
z & h::winR(659,"h","z & h")
z & i::winR(660,"i","z & i")
z & j::winR(661,"j","z & j")
z & k::winR(662,"k","z & k")
z & l::winR(663,"l","z & l")
z & m::winR(664,"m","z & m")
z & n::winR(665,"n","z & n")
z & o::winR(666,"o","z & o")
z & p::winR(667,"p","z & p")
z & q::winR(668,"q","z & q")
z & r::winR(669,"r","z & r")
z & s::winR(670,"s","z & s")
z & t::winR(671,"t","z & t")
z & u::winR(672,"u","z & u")
z & v::winR(673,"v","z & v")
z & w::winR(674,"w","z & w")
z & x::winR(675,"x","z & x")
z & y::winR(676,"y","z & y")


esc::ExitApp, 10086
#if




